(()=>{const $=s=>document.querySelector(s);let SUPPLIERS=[],PROFILES=[],PRODUCTS=[],ORDERS=[];
const msg=(t,b=false)=>{const e=$('#status');e.textContent=t;e.className='status'+(b?' bad':'')};
function go(v){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('on',b.dataset.view===v));document.querySelectorAll('.view').forEach(x=>x.hidden=true);$('#view-'+v).hidden=false}
async function verifyAdmin(){const s=IZZY.session();if(!s?.user?.id)throw Error('Please log in.');const roles=await IZZY.request(`/rest/v1/user_roles?select=role&user_id=eq.${encodeURIComponent(s.user.id)}`);if(!roles.some(r=>r.role==='admin'))throw Error('Admin access required.')}
function renderSuppliers(){const pm=new Map(PROFILES.map(p=>[p.id,p]));$('#suppliers').innerHTML=SUPPLIERS.map(s=>{const p=pm.get(s.profile_id)||{};return `<div class="list-row"><div class="row"><div><b>${IZZY.esc(s.business_name)}</b><small>${IZZY.esc(p.full_name||'')} · ${IZZY.esc(p.phone||'')}</small></div><span class="tag ${s.status==='approved'?'ok':s.status==='pending'?'warn':''}">${IZZY.esc(s.status)}</span></div>${s.status==='pending'?`<div class="hero-actions"><button class="btn review-btn" data-id="${s.id}" data-decision="approve">Approve</button><button class="btn secondary review-btn" data-id="${s.id}" data-decision="reject">Reject</button></div>`:s.status==='approved'?`<div class="hero-actions"><button class="btn secondary review-btn" data-id="${s.id}" data-decision="suspend">Suspend</button></div>`:''}</div>`}).join('')||'<div class="notice">No supplier applications yet.</div>';document.querySelectorAll('.review-btn').forEach(b=>b.onclick=()=>review(b))}
function renderProducts(){$('#products').innerHTML=PRODUCTS.map(p=>`<div class="list-row row"><div><b>${IZZY.esc(p.name)}</b><small>${IZZY.esc(p.sku)} · ${IZZY.money(p.suggested_retail_price,p.currency)}</small></div><span class="tag ${p.status==='active'?'ok':''}">${IZZY.esc(p.status)}</span></div>`).join('')||'<div class="notice">No products yet.</div>'}
function renderOrders(){$('#orders').innerHTML=ORDERS.map(o=>`<div class="list-row row"><div><b>${IZZY.esc(o.external_order_ref||o.shopify_order_name||('Order '+String(o.id).slice(0,8)))}</b><small>${IZZY.esc(o.customer_name||'')} · ${IZZY.money(o.total_amount,o.currency)} · ${new Date(o.created_at).toLocaleString()}</small></div><span class="tag ${o.status==='fulfilled'?'ok':''}">${IZZY.esc(o.status)}</span></div>`).join('')||'<div class="notice">No orders yet.</div>'}
async function review(btn){btn.disabled=true;try{await IZZY.rpc('admin_review_supplier',{_supplier_id:btn.dataset.id,_decision:btn.dataset.decision});msg('Supplier updated.');await load()}catch(e){msg(e.message,true);btn.disabled=false}}
async function load(){[SUPPLIERS,PROFILES,PRODUCTS,ORDERS]=await Promise.all([IZZY.request('/rest/v1/suppliers?select=*&order=created_at.desc'),IZZY.request('/rest/v1/profiles?select=id,full_name,phone,business_name,created_at'),IZZY.request('/rest/v1/supplier_products?select=*&order=created_at.desc'),IZZY.request('/rest/v1/orders?select=*&order=created_at.desc&limit=100')]);renderSuppliers();renderProducts();renderOrders();msg('Admin backend connected.')}
$('#logout').onclick=()=>{IZZY.logout();location.href='login.html'};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));
(async()=>{try{await verifyAdmin();await load()}catch(e){msg(e.message,true);setTimeout(()=>location.href='login.html',1200)}})();})();