(()=>{
  const $=s=>document.querySelector(s);let PRODUCTS=[],LINKS=[],ORDERS=[],SESSION=null;
  const status=(t,b=false)=>{const e=$('#dash-status');e.textContent=t;e.className='status'+(b?' bad':'')};
  function go(v){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('on',b.dataset.view===v));document.querySelectorAll('.view').forEach(x=>x.hidden=true);$('#view-'+v).hidden=false}
  function renderProducts(){const q=$('#product-search').value.toLowerCase(),linked=new Set(LINKS.map(x=>x.supplier_product_id));const a=PRODUCTS.filter(p=>(p.name+' '+(p.description||'')+' '+(p.sku||'')).toLowerCase().includes(q));$('#products').innerHTML=a.map(p=>`<article class="card product-card"><div class="product-image">${p.primary_image_url?`<img src="${IZZY.esc(p.primary_image_url)}" alt="">`:'IZ'}</div><div class="product-body"><span class="tag ${Number(p.stock_quantity)>0?'ok':'warn'}">${Number(p.stock_quantity)>0?`${p.stock_quantity} in stock`:'Out of stock'}</span><h3>${IZZY.esc(p.name)}</h3><p>${IZZY.esc(p.description||'Ready for your store.')}</p><div class="product-meta"><span class="price">${IZZY.money(p.suggested_retail_price,p.currency)}</span><span class="sku">${IZZY.esc(p.sku||'')}</span></div><button class="btn link-btn" data-id="${p.product_id}" data-slug="${IZZY.esc(p.public_slug)}">${linked.has(p.product_id)?'Get product link':'Link to your web'}</button></div></article>`).join('')||'<div class="notice">No products found.</div>';document.querySelectorAll('.link-btn').forEach(b=>b.onclick=()=>linkProduct(b))}
  function renderLinked(){const map=new Map(PRODUCTS.map(p=>[p.product_id,p]));$('#linked').innerHTML=LINKS.map(l=>{const p=map.get(l.supplier_product_id)||{};return `<div class="list-row row"><div><b>${IZZY.esc(p.name||'Product')}</b><small>${IZZY.money(l.retail_price||p.suggested_retail_price,p.currency)} · ${IZZY.esc(p.public_slug||'')}</small></div><button class="btn secondary link-btn" data-id="${l.supplier_product_id}" data-slug="${IZZY.esc(p.public_slug||'')}">Copy link</button></div>`}).join('')||'<div class="notice">You have not linked any products yet.</div>';document.querySelectorAll('#linked .link-btn').forEach(b=>b.onclick=()=>openLink(b.dataset.slug))}
  function renderOrders(){$('#orders').innerHTML=ORDERS.map(o=>`<div class="list-row row"><div><b>${IZZY.esc(o.external_order_ref||o.shopify_order_name||('Order '+o.id.slice(0,8)))}</b><small>${IZZY.money(o.total_amount,o.currency)} · ${IZZY.esc(o.source||'manual')} · ${new Date(o.created_at).toLocaleDateString()}</small></div><span class="tag">${IZZY.esc(o.status)}</span></div>`).join('')||'<div class="notice">No orders yet.</div>'}
  function renderOrderProducts(){const map=new Map(PRODUCTS.map(p=>[p.product_id,p]));const el=$('#order-product');if(!el)return;const current=el.value;el.innerHTML='<option value="">Choose one of My products</option>'+LINKS.map(l=>{const p=map.get(l.supplier_product_id);return p?`<option value="${IZZY.esc(p.product_id)}">${IZZY.esc(p.name)}</option>`:''}).join('');if([...el.options].some(o=>o.value===current))el.value=current}
  async function loadOrderVariants(){const productId=$('#order-product').value,el=$('#order-variant');el.innerHTML='<option value="">Choose variant</option>';el.disabled=true;if(!productId)return;try{const vs=await IZZY.rpc('marketplace_variants',{_product_id:productId});el.innerHTML='<option value="">Choose variant</option>'+vs.map(v=>`<option value="${IZZY.esc(v.id)}" ${Number(v.stock_quantity)<=0?'disabled':''}>${IZZY.esc(v.variant_name||v.sku||'Default')} · ${v.stock_quantity} in stock</option>`).join('');el.disabled=false}catch(e){$('#order-status').textContent=e.message;$('#order-status').className='status bad'}}
  function openLink(slug){const u=IZZY.productUrl(slug);$('#product-link').value=u;$('#copy-status').textContent='';$('#link-modal').hidden=false}
  async function linkProduct(b){b.disabled=true;b.textContent='Linking…';try{await IZZY.rpc('link_product_to_web',{_product_id:b.dataset.id,_retail_price:null});await load();openLink(b.dataset.slug);status('Product added to My IzzyDrop products.')}catch(e){status(e.message,true)}finally{b.disabled=false}}
  async function load(){try{[PRODUCTS,LINKS,ORDERS]=await Promise.all([IZZY.rpc('marketplace_catalog_v2'),IZZY.request('/rest/v1/dropshipper_product_links?select=*&order=created_at.desc'),IZZY.request('/rest/v1/orders?select=*&order=created_at.desc&limit=50')]);$('#stat-products').textContent=PRODUCTS.length;$('#stat-linked').textContent=LINKS.length;$('#stat-orders').textContent=ORDERS.length;renderProducts();renderLinked();renderOrders();renderOrderProducts();status('IzzyDrop dropshipper system connected. No Shopify required.')}catch(e){status(e.message,true)}}
  async function showDash(){SESSION=IZZY.session();if(!SESSION?.access_token){location.href='login.html';return}const rows=await IZZY.request(`/rest/v1/dropshippers?select=id,status&profile_id=eq.${encodeURIComponent(SESSION.user.id)}&limit=1`);if(!rows?.length){location.href='login.html';return}$('#gate').hidden=true;$('#dashboard').hidden=false;$('#user-email').textContent=SESSION?.user?.email||'Signed in';await load()}
    $('#product-search').oninput=renderProducts;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));$('#close-modal').onclick=()=>$('#link-modal').hidden=true;$('#copy-link').onclick=async()=>{try{await navigator.clipboard.writeText($('#product-link').value);$('#copy-status').textContent='Copied.'}catch{$('#product-link').select();document.execCommand('copy');$('#copy-status').textContent='Copied.'}};
  $('#order-product').onchange=loadOrderVariants;
  $('#order-form').onsubmit=async e=>{e.preventDefault();const s=$('#order-status'),btn=$('#order-submit');btn.disabled=true;btn.textContent='Sending…';s.textContent='Creating order…';s.className='status';try{const orderId=await IZZY.rpc('create_dropshipper_order',{_product_id:$('#order-product').value,_variant_id:$('#order-variant').value,_quantity:Number($('#order-qty').value||1),_customer_name:$('#order-customer-name').value.trim(),_customer_phone:$('#order-customer-phone').value.trim(),_customer_email:$('#order-customer-email').value.trim()||null,_shipping_address:{address1:$('#order-address1').value.trim(),city:$('#order-city').value.trim(),governorate:$('#order-governorate').value.trim()},_external_order_ref:$('#order-ref').value.trim()||null});s.textContent='IzzyDrop order created ✓ '+String(orderId).slice(0,8);$('#order-form').reset();$('#order-variant').innerHTML='<option value="">Choose variant</option>';$('#order-variant').disabled=true;await load()}catch(err){s.textContent=err.message;s.className='status bad'}finally{btn.disabled=false;btn.textContent='Send order to IzzyDrop'}};
  showDash().catch(e=>{const g=$('#gate-message');if(g){g.textContent=e.message;g.style.color='var(--bad)'}});
})();