(()=>{const $=s=>document.querySelector(s);let SUP=null,PRODUCTS=[],VARIANTS=[],IMAGES=[],ORDERS=[],ITEMS=[],SELECTED_IMAGES=[];const msg=(t,b=false)=>{const e=$('#status');if(e){e.textContent=t;e.className='status'+(b?' bad':'')}};function go(v){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('on',b.dataset.view===v));document.querySelectorAll('.view').forEach(x=>x.hidden=true);$('#view-'+v).hidden=false}
async function verify(){const s=IZZY.session();if(!s?.user?.id){location.href='login.html';return false}let rows=await IZZY.request(`/rest/v1/suppliers?select=id,business_name,status&profile_id=eq.${encodeURIComponent(s.user.id)}&limit=1`);SUP=rows?.[0];if(!SUP){const prof=await IZZY.request(`/rest/v1/profiles?select=business_name,requested_account_type&id=eq.${encodeURIComponent(s.user.id)}&limit=1`);if(prof?.[0]?.requested_account_type==='supplier'){const created=await IZZY.request('/rest/v1/suppliers',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({profile_id:s.user.id,business_name:prof[0].business_name||s.user.email,status:'pending'})});SUP=created?.[0]}}if(!SUP){location.href='login.html';return false}if(SUP.status!=='approved'){const g=$('#gate-message');g.textContent=SUP.status==='pending'?'Your IzzyDrop supplier application is waiting for admin approval.':'Your IzzyDrop supplier account is '+SUP.status+'.';return false}$('#gate').hidden=true;$('#supplier').hidden=false;$('#business').textContent=SUP.business_name;await load();return true}
function renderProducts(){const vm=new Map,im=new Map;VARIANTS.forEach(v=>{if(!vm.has(v.product_id))vm.set(v.product_id,[]);vm.get(v.product_id).push(v)});IMAGES.forEach(i=>{if(!im.has(i.product_id)||Number(i.position)<Number(im.get(i.product_id).position))im.set(i.product_id,i)});$('#products').innerHTML=PRODUCTS.map(p=>{const pic=im.get(p.id);return `<div class="list-row supplier-product-row"><div class="supplier-product-thumb">${pic?.url?`<img src="${IZZY.esc(pic.url)}" alt="">`:'IZ'}</div><div class="supplier-product-copy"><div class="row"><div><b>${IZZY.esc(p.name)}</b><small>${IZZY.esc(p.sku)} · ${IZZY.money(p.suggested_retail_price,p.currency)}</small></div><span class="tag ${p.status==='active'?'ok':''}">${IZZY.esc(p.status)}</span></div>${(vm.get(p.id)||[]).map(v=>`<small>${IZZY.esc(v.variant_name||'Default')}: ${Number(v.stock_quantity||0)} in stock</small>`).join('')}<small>${IMAGES.filter(i=>i.product_id===p.id).length} photo${IMAGES.filter(i=>i.product_id===p.id).length===1?'':'s'}</small></div></div>`}).join('')||'<div class="notice">No products yet.</div>'}
function renderOrders(){const pm=new Map(PRODUCTS.map(p=>[p.id,p]));const om=new Map(ORDERS.map(o=>[o.id,o]));const open=ITEMS.filter(i=>!['fulfilled','cancelled'].includes(i.fulfillment_status)).length;$('#order-count').textContent=open;$('#orders').innerHTML=ITEMS.map(i=>{const o=om.get(i.order_id)||{},p=pm.get(i.supplier_product_id)||{},addr=o.shipping_address||{};const fulfilled=i.fulfillment_status==='fulfilled';return `<div class="list-row supplier-order"><div class="row"><div><b>${IZZY.esc(p.name||'Product')} × ${Number(i.quantity||1)}</b><small>${IZZY.esc(o.external_order_ref||o.shopify_order_name||('Order '+String(o.id||'').slice(0,8)))} · ${IZZY.money(i.retail_price_at_purchase,o.currency||'EGP')}</small></div><span class="tag ${fulfilled?'ok':''}">${IZZY.esc(i.fulfillment_status)}</span></div><div class="notice" style="margin-top:12px"><b>Customer:</b> ${IZZY.esc(o.customer_name||'—')} · ${IZZY.esc(o.customer_phone||'—')}<br><b>Address:</b> ${IZZY.esc([addr.address1,addr.city,addr.governorate].filter(Boolean).join(', ')||'—')}</div>${fulfilled?`<small style="margin-top:10px">Tracking: ${IZZY.esc(i.shipping_carrier||'—')} ${IZZY.esc(i.tracking_number||'')}</small>`:`<div class="form" style="margin-top:12px"><div class="row"><input data-carrier="${i.id}" placeholder="Shipping carrier" style="flex:1"><input data-tracking="${i.id}" placeholder="Tracking number" style="flex:1"></div><button class="btn fulfill-btn" data-id="${i.id}">Mark fulfilled</button></div>`}</div>`}).join('')||'<div class="notice">No supplier orders yet.</div>';document.querySelectorAll('.fulfill-btn').forEach(b=>b.onclick=()=>fulfill(b))}
async function fulfill(btn){const id=btn.dataset.id,carrier=document.querySelector(`[data-carrier="${id}"]`)?.value?.trim()||null,tracking=document.querySelector(`[data-tracking="${id}"]`)?.value?.trim()||null;btn.disabled=true;btn.textContent='Updating…';try{await IZZY.rpc('supplier_fulfill_order_item',{_order_item_id:id,_tracking_number:tracking,_shipping_carrier:carrier});msg('Order item marked fulfilled.');await load()}catch(e){msg(e.message,true);btn.disabled=false;btn.textContent='Mark fulfilled'}}
async function load(){[PRODUCTS,VARIANTS,IMAGES,ORDERS,ITEMS]=await Promise.all([IZZY.request(`/rest/v1/supplier_products?select=*&supplier_id=eq.${SUP.id}&order=created_at.desc`),IZZY.request('/rest/v1/product_variants?select=*&order=created_at.desc'),IZZY.request('/rest/v1/product_images?select=*&order=position.asc'),IZZY.request('/rest/v1/orders?select=*&order=created_at.desc&limit=100'),IZZY.request(`/rest/v1/order_items?select=*&supplier_id=eq.${SUP.id}&order=created_at.desc&limit=100`)]);$('#product-count').textContent=PRODUCTS.length;$('#active-count').textContent=PRODUCTS.filter(p=>p.status==='active').length;$('#stock-count').textContent=VARIANTS.reduce((n,v)=>n+Number(v.stock_quantity||0),0);renderProducts();renderOrders();msg('IzzyDrop supplier system connected.')}
function renderSelectedImages(){
  const box=$('#p-image-preview');
  if(!SELECTED_IMAGES.length){box.innerHTML='<div class="photo-empty">No photos selected yet.</div>';return}
  box.innerHTML=SELECTED_IMAGES.map((f,i)=>`<div class="photo-preview"><img src="${URL.createObjectURL(f)}" alt=""><span>${i===0?'Main photo':`Photo ${i+1}`}</span></div>`).join('');
}
$('#p-images').onchange=e=>{
  const files=[...e.target.files];
  const allowed=['image/jpeg','image/png','image/webp'];
  if(files.length>6){msg('Choose up to 6 product photos.',true);e.target.value='';SELECTED_IMAGES=[];renderSelectedImages();return}
  const bad=files.find(f=>!allowed.includes(f.type)||f.size>5*1024*1024);
  if(bad){msg('Photos must be JPG, PNG, or WebP and no larger than 5 MB each.',true);e.target.value='';SELECTED_IMAGES=[];renderSelectedImages();return}
  SELECTED_IMAGES=files;renderSelectedImages();msg(files.length?`${files.length} product photo${files.length===1?'':'s'} ready to upload.`:'');
};
$('#add-form').onsubmit=async e=>{
  e.preventDefault();
  const btn=$('#add-product-btn');btn.disabled=true;btn.textContent='Adding product…';
  try{
    const name=$('#p-name').value.trim(),sku=$('#p-sku').value.trim(),cost=Number($('#p-cost').value),retail=Number($('#p-retail').value),stock=Number($('#p-stock').value),description=$('#p-description').value.trim(),photoCount=SELECTED_IMAGES.length;
    const pr=await IZZY.request('/rest/v1/supplier_products',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({supplier_id:SUP.id,name,sku,description:description||null,cost_price:cost,suggested_retail_price:retail,currency:'EGP',status:'draft'})});
    const p=pr?.[0];if(!p?.id)throw Error('Could not create product.');
    await IZZY.request('/rest/v1/product_variants',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({product_id:p.id,variant_name:'Default',sku,cost_price:cost,stock_quantity:stock})});
    for(let i=0;i<SELECTED_IMAGES.length;i++){
      btn.textContent=`Uploading photo ${i+1} of ${SELECTED_IMAGES.length}…`;
      const file=SELECTED_IMAGES[i],ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';
      const path=`${SUP.id}/${p.id}/${String(i+1).padStart(2,'0')}-${Date.now()}.${ext}`;
      const url=await IZZY.uploadProductImage(path,file);
      await IZZY.request('/rest/v1/product_images',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({product_id:p.id,url,position:i})});
    }
    await IZZY.request(`/rest/v1/supplier_products?id=eq.${p.id}`,{method:'PATCH',body:JSON.stringify({status:'active'})});
    e.target.reset();SELECTED_IMAGES=[];renderSelectedImages();msg(photoCount?`Product added with ${photoCount} photo${photoCount===1?'':'s'}.`:'Product added successfully.');go('products');await load()
  }catch(err){msg(err.message,true)}
  finally{btn.disabled=false;btn.textContent='Add product'}
};
$('#logout').onclick=()=>{IZZY.logout();location.href='login.html'};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));(async()=>{try{await verify()}catch(e){const g=$('#gate-message');if(g){g.textContent=e.message;g.style.color='var(--bad)'}}})();})();